FishtechCSOC/.github

PULL_REQUEST_TEMPLATE.md

feat: add better formating

---

.github/actions/helm-push/Dockerfile
.github/actions/helm-push/action.yaml
.github/actions/helm-push/entrypoint.sh
.github/workflows/helm-build.yaml
.github/workflows/helm-deploy-dev.yaml

- Adding actions/helm-push for pushing to Artifact Registry
- Adding helm-build and helm-deploy-dev
- Support reusable workflows

chore: adding helm-push action and helm-build, helm-deploy-dev

---

.github/workflows/helm-deploy-dev.yaml

chore: removing auto sync policy for dev deploy

---

.github/workflows/helm-build.yaml
.github/workflows/helm-deploy-dev.yaml
.github/workflows/helm-deploy-prod.yaml

- Adding inputs for `APP_VERSION`, `GCP_ARTIFACT_REGISTRY`, and `ARGOCD_REPO`
- Moving Helm packaging to deploy workflows
- Match image tags in Helm charts with GitHub release tags

chore: adding default values for artifact registry and appversion

---

.github/workflows/helm-build.yaml
.github/workflows/helm-deploy-dev.yaml
.github/workflows/helm-deploy-prod.yaml

Devops 919 fix workflow depth

---

.github/workflows/helm-deploy-dev.yaml
.github/workflows/helm-deploy-prod.yaml

chore: removing helm-package dependency from deploy workflows

---

.github/workflows/helm-deploy-dev.yaml
.github/workflows/helm-deploy-prod.yaml

chore: adding RespectIgnoreDifferences

---

.github/workflows/helm-deploy-dev.yaml

chore: adding argocd app restart to dev only

---

.github/workflows/helm-deploy-prod.yaml

chore: adding app deployment action to prod argocd deploy

---

.github/workflows/kaniko-build-generic.yaml
.github/workflows/kaniko-build-node.yaml
.github/workflows/kaniko-push-generic.yaml
.github/workflows/kaniko-push-node.yaml

- Adding `kaniko-build-node` and `kaniko-push-node` reusable workflows
- Adding `kaniko-build-generic` and `kaniko-push-generic` reusable workflows

chore: adding kaniko build and push workflows

---

PULL_REQUEST_TEMPLATE.md

refactor: update pr template

---

.github/workflows/kaniko-build-node.yaml

- Making `npm test` and `npm lint` steps optional
`comment here`
`comment here`
- feat
- fix
- docs
- style
- refactor
- perf
- test
- build
- ci
- chore
- revert

Devops 1010 npm test toggle

---

PULL_REQUEST_TEMPLATE.md

fix spelling
`comment here`
`comment here`
- feat
- fix
- docs
- style
- refactor
- perf
- test
- build
- ci
- chore
- revert

chore: fix spelling

---

.github/workflows/helm-check.yaml
.github/workflows/kaniko-build-node.yaml

`comment here`
`comment here`
`comment here`
- feat
- fix
- docs
- style
- refactor
- perf
- test
- build
- ci
- chore
- revert

Devops 1027 enable cache toggling

---

.github/workflows/helm-deploy.yaml
.github/workflows/helm-package.yaml

`comment here`
`comment here`
`comment here`
- feat
- fix
- docs
- style
- refactor
- perf
- test
- build
- ci
- chore
- revert

Devops 1027 enable custom app name

---

.github/workflows/helm-deploy.yaml

`comment here`
`comment here`
`comment here`
- feat
- fix
- docs
- style
- refactor
- perf
- test
- build
- ci
- chore
- revert

Devops 1027 add release input

---

PULL_REQUEST_TEMPLATE.md

Changing the default PR template a bit
I feel like some of the information is unnecessary and the ordering isn't ideal
not really

chore: PR template update

---

.github/CODEOWNERS

Adding eng leadership team as code owners

chore: Update CODEOWNERS to include eng leadership

---

.github/workflows/pr-requirements.yaml

adding a workflow to perform PR requirements checks
New workflow
no
no

feat: adding PR requirements workflow

---

workflow-templates/pr-requirements.properties.json
workflow-templates/pr-requirements.yaml
workflow-templates/readme.md

moving pr requirements to workflow templates

feat: moving pr requirements workflow to templates
